spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/design_coding_task
    driverClassName: org.postgresql.Driver
    username: client
    password: client
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9091
    consumer:
      group-id: design-coding-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer